### ISSUE TITLE
Autocompletion breaks with non-alphanumeric characters

### ISSUE THREAD

**Issue by tbtommyb** [a-la-node/autocomplete#47]
E.g you'll get suggestions when typing 'he' but if you type 'he\\' they stop.

The server strips all non-alphanumeric characters before searching for words and if you look at network activity in dev tools you can see that it's correctly sending back responses that are valid for the input with the non-alphanumeric characters stripped out.

So possibly this is a bug in the Chrome implementation of datalist but I'm not sure how to investigate further.

**Comment by Cleop** [comment]
This doesn't seem to happen for me?  This was due to datalist. So this is now fine.
